### ISSUE TITLE
Params declared with certain types will not trigger updates on change.

### ISSUE THREAD

**Issue by mthadley** [metal/metal-tools-soy#10]
I noticed that when I add a param with a record type:
```soy
{@param item: [label: string, id: number]}
```
...My component won't update if `item` changes.

I know we have a default `shouldUpdate` implementation for `metal-soy`components (see [here](https://github.com/metal/metal.js/blob/master/packages/metal-soy/src/Soy.js#L179)), and I think this is returning false because `item` is not being parsed as being a `@param` to the template.

Looking at the regex used by `soyparser` (see [here](https://github.com/mairatma/soyparser/blob/master/index.js#L16)), it looks like the regex will not match that kind of type declaration. I'm guessing there might be a few other corner cases related to type declarations that might also lead to this problem.

**Comment by jbalsas** [comment]
Just for reference, because @mthadley already knows, we're moving to a new, more robust soyparser:

https://github.com/metal/soyparser

Unless someone beats me to it, I'll work on integrating it on monday.

**Comment by jbalsas** [comment]
Fixed via https://github.com/metal/metal-tools-soy/commit/fe63d17df39c2a83465b9b2f11b704d8949a37c7
