### ISSUE TITLE
Unsupported major.minor version 52.0

### ISSUE THREAD

**Issue by bryceosterhaus** [metal/metal-tools-soy#2]
I was trying to build metal-modal and got the error

`Exception in thread "main" java.lang.UnsupportedClassVersionError: com/google/template/soy/SoyToIncrementalDomSrcCompiler : Unsupported major.minor version 52.0`

Java Version 8 Update 45 (build 1.8.0_45-b14)

**Comment by mairatma** [comment]
Are you sure that you're using Java 8? This error complains about Java version, and so far I've never seen it with Java 8. You may have more than one java on your machine, with another as the default.

My java version: 

```
java version "1.8.0_31"
Java(TM) SE Runtime Environment (build 1.8.0_31-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.31-b07, mixed mode)
```

**Comment by bryceosterhaus** [comment]
You're right, I had a different version running for my user than what I have globally which caused me to mix it up.

Thanks!
