### ISSUE TITLE
Aggregate Soy Tooling in this repo

### ISSUE THREAD

**Issue by jbalsas** [metal/metal-tools-soy#35]
We should try to convert this to a lerna monorepo to aggregate all related soy tooling for a simpler tracking and management.

Current Soy Tooling we own includes:
- [metal-soy-critic](https://github.com/metal/metal-soy-critic)
- [soyparser](https://github.com/metal/soyparser)
- [gulp-soynode](https://github.com/metal/gulp-soynode) - consider removal?
- [metal-tools-soy](https://github.com/metal/metal-tools-soy)
- [metal-soy-loader](https://github.com/metal/metal-soy-loader)
- [generate-soy-source-maps](https://github.com/matuzalemsteles/generate-soy-source-maps)

**Comment by matuzalemsteles** [comment]
hey @jbalsas, I think we can remove `gulp-soynode`.  Do you still have plans for it?

Just a few thoughts I had, what do you think of the nomenclatures for publishing in NPM? I know this would have a breaking change, but we can send out [notices to replace](https://docs.npmjs.com/cli/deprecate)... are easier to find and centralize.

* **@metal/soy-sourcemap** - generate-soy-source-maps
* **@meta/soy-critic** - metal-soy-critic
* **@metal/soy-compiler** - metal-tools-soy
* **@metal/soy-loader** - metal-soy-loader
* **@metal/soy-parser** - soyparser

**Comment by jbalsas** [comment]
Hey @matuzalemsteles, I think `gulp-soynode` is still used by `metal-cli`... we can leave it where it is for now and deprecate in the future.

I think we can indeed normalize the names... I'm not so sure about the `@metal` organization. These are in many cases not really metal-specific (only `soy-compiler`). 

@zenorocha, what do you think? Can you think of a good naming schema for this?

**Comment by matuzalemsteles** [comment]
@jbalsas

> I think we can indeed normalize the names... I'm not so sure about the @metal organization. These are in many cases not really metal-specific (only soy-compiler).

Oh yes, truth.

**Comment by jbalsas** [comment]
This is now officially done! 👍
