### ISSUE TITLE
Doesn’t work correctly with files with windows-style line-endings (CRLF)

### ISSUE THREAD

**Issue by yuchi** [metal/metal-tools-soy#4]
We found the issue developing a Liferay tag(lib) with Soy. You can replicate the issue in a Liferay module and forcing the line-endings to be CRLF:

```
$ unix2dos src/main/resources/META-INF/resources/MyTemplate.soy
$ gradle clean build
... ... ...
> Building 67% > :modules:my-project:transpileJS
Running 'build'...
Compiling soy

stream.js:74
      throw er; // Unhandled stream error in pipe.
      ^
Error: Compile error:
errors during Soy compilation
In file drop_area/DropArea.soy:1:23: parse error at '
': expected eof, {alias, {deltemplate, or {template
{namespace MyTemplate}
                      ^


:modules:tools-osgi:adr-frontend-taglib:transpileJS FAILED
... ... ...
BUILD FAILED

Total time: 17.777 secs
```

And obviously you can replicate the fix:

```
$ dos2unix src/main/resources/META-INF/resources/MyTemplate.soy
$ gradle clean build
... ... ...
BUILD SUCCESSFUL

Total time: 18.755 secs
```

**Comment by yuchi** [comment]
Replicated the issue in a clean clone of this package:

```
$ git clone https://github.com/metal/metal-tools-soy.git
$ cd metal-tools-soy
$ npm install
... ... ...
$ unix2dos test/fixtures/soy/*.soy
$ npm test

> metal-tools-soy@3.0.2 test /Users/pier/Development/metal-tools-soy
> mocha test/*.js test/lib/**/*.js --slow 1000 --timeout 3000

  Metal Tools - Soy
    ✓ should compile soy files from/to "src" folder by default
    ✓ should consume stream by default
    ✓ should not consume stream if skipConsume is set to true
    Integration
Error in plugin 'metal-tools-soy'
Message:
    Compile error:
errors during Soy compilation
In file test/fixtures/soy/simple.soy:1:19: parse error at '
': expected eof, {alias, {deltemplate, or {template
{namespace Simple}
                  ^


      1) should compile specified soy files to js
... ... ...
```

**Comment by yuchi** [comment]
Surprisingly this is _not_ an issue with `soyparser`, which is what I originally thought.

**Comment by mairatma** [comment]
Yes, we're aware of this problem, it's a problem with google's soy compiler. We're waiting for a fix from them in this issue: https://github.com/google/closure-templates/issues/111.

**Comment by yuchi** [comment]
Gosh, thanks.

**Comment by yuchi** [comment]
This has been solved: https://github.com/google/closure-templates/commit/7dae5a1a2b6868da939e7643741b67db1610f190

/cc @mairatma @eduardolundgren

**Comment by eduardolundgren** [comment]
@yuchi thanks for letting us know, @brunobasto is responsible for updating closure templates into Metal.js, he will give us a summary of how this new version goes.

**Comment by brunobasto** [comment]
Thanks for letting us know @yuchi. I'll update it and let you know.

**Comment by yuchi** [comment]
Sorry @brunobasto for not mentioning you, I still have issues on who's owner of what 😅

**Comment by brunobasto** [comment]
No problem :) I just built closure-templates and it looks like the generated jar does solve the issue. Will be releasing it soon..

**Comment by yuchi** [comment]
Great!! Thanks to all! Gonna update ASAP and remove a lot of troubles
