### ISSUE TITLE
[metal-tools-soy]goog.require regex on replaceTemplateRequires isn't working correctly with dotted namespaces

### ISSUE THREAD

**Issue by diegonvs** [metal/metal-tools-soy#42]
Try execute the regex described at this [line](https://github.com/metal/metal-tools-soy/blob/master/lib/pipelines/compileSoy.js#L249) on this closure-templates generated file: https://gist.github.com/diegonvs/432de495b3a5318bd68bffc86364ff69

If you remove the dots on namespace the regex will catch the `goog.require` lines.

**Comment by jbalsas** [comment]
Hey @diegonvs, we already have tests for this: https://github.com/metal/metal-tools-soy/blob/master/test/fixtures/soy/CompoundName.soy and this is being used throughout Liferay Portal with `metal-cli` already... could you please double check? Looks like this might be a different error.

**Comment by diegonvs** [comment]
@jbalsas, Apparently we don't have tests when a compound file is calling another compound file using`goog.require`.

Compile these three dependant files: 
- https://gist.github.com/diegonvs/ce4fb56c26911ef202ac8c21b5cea51e
- https://gist.github.com/diegonvs/a66a24a71aa771515e5f2d99824b1e04
- https://gist.github.com/diegonvs/c224e8db462ee20d8af71ca64243d308

And see the generated Layout(parent) .soy.js file:

Using the current requireRegex there are some errors:
```javascript
      var incrementalDom = goog.require('incrementaldom');
      var soyIdom = goog.require('soy.idom');
      var $import1 = goog.require('com.liferay.layout.admin.web.LayoutBreadcrumbs.incrementaldom');
      var $templateAlias1 = Soy.getTemplate('undefined.incrementaldom', 'render');
      var $import2 = goog.require('com.liferay.layout.admin.web.LayoutColumn.incrementaldom');
      var $templateAlias2 = Soy.getTemplate('undefined.incrementaldom', 'render');
```
When using replaceTemplateRequires with the current requireRegex the namespace of files is being lost.

However, accepting not only letters but letters followed by dots on the requireRegex pattern this problem is being solved.

**Comment by jbalsas** [comment]
Interesting... are those existing templates? If so... they're already being compiled by `metal-tools-soy`, aren't they? Feels like there must be something else at play here. I'm not saying we should not add this fix, but I'm wondering what it is we currently have in place that we won't anymore that's causing this to show up now.

Maybe we were doing some other replacement or a different compilation somewhere else? Could you check to see what version of `metal-tools-soy` is being used there?

**Comment by jbalsas** [comment]
Closing here since we won't be moving to `6.x`. We'll stay in `4.x` for the remaining life span of `metal-tools-soy`
