### ISSUE TITLE
`tmp/metal-tools-soy/` folder is always created at the root of the drive

### ISSUE THREAD

**Issue by blzaugg** [metal/metal-tools-soy#48]
When I build Liferay Portal `master`, a `tmp/metal-tools-soy/` folder is always created at the root of the drive.

I assume this is an issue of `metal-tools-soy` rather than Portal.

**Comment by blzaugg** [comment]
I'm guessing this line:

https://github.com/metal/metal-tools-soy/blob/dcd8845cdddfc0f665ad529cc3a79e06029c7b0a/lib/options.js#L6

**Comment by julien** [comment]
I guess it was meant to be 

```javascript
outputDir: `${os.tmpdir()}${path.sep}metal-tools-soy`
```

**Comment by blzaugg** [comment]
I saw another file use `tmp` explicitly:
https://github.com/metal/metal-tools-soy/blob/dcd8845cdddfc0f665ad529cc3a79e06029c7b0a/lib/pipelines/__tests__/compileSoy.js#L11

**Comment by julien** [comment]
@blzaugg in this case, I guess that's a directory created especially for test purposes, which is [deleted](https://github.com/metal/metal-tools-soy/blob/dcd8845cdddfc0f665ad529cc3a79e06029c7b0a/lib/pipelines/__tests__/compileSoy.js#L27-L31) once the tests have finished.

**Comment by blzaugg** [comment]
Ah.

**Comment by jbalsas** [comment]
Published in `4.3.1`
